name = "stylo-api"
main = "src/index.ts"
compatibility_date = "2024-10-26"
compatibility_flags = [ "nodejs_compat" ]

[placement]
mode = "smart"

[ai]
binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1