name = "stylo-api"
main = "src/index.ts"
compatibility_date = "2024-10-26"
compatibility_flags = [ "nodejs_compat" ]

[placement]
mode = "smart"

[ai]
binding = "AI"

[observability]
enabled = true
head_sampling_rate = 1

[[kv_namespaces]]
binding = "HISTORY_KV"
id = "efd83beca3174ee2ba9bdeaf99f73b4d"

[[d1_databases]]
binding = "HISTORY_DB"
database_name = "prod-d1-history"
database_id = "482cf989-efd8-45ae-a3cd-5e5891a0e573"